"""Aggiunta chunk_number a transcription_chunks

Revision ID: 0053fc0bb891
Revises: 526d0157cd53
Create Date: 2025-02-14 12:46:22.785642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0053fc0bb891'
down_revision: Union[str, None] = '526d0157cd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_chunks', sa.Column('chunk_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_chunks', 'chunk_number')
    # ### end Alembic commands ###
