"""Correzione 3, relazione tra transcripts e transcription_chunks

Revision ID: 11ce52399412
Revises: 54706a9af6a8
Create Date: 2025-02-14 12:40:37.738034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ce52399412'
down_revision: Union[str, None] = '54706a9af6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transcripts_chunk_fkey', 'transcripts', type_='foreignkey')
    op.drop_column('transcripts', 'chunk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('chunk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transcripts_chunk_fkey', 'transcripts', 'transcription_chunks', ['chunk'], ['id'])
    # ### end Alembic commands ###
