"""Correzione relazione transcripts-chunks

Revision ID: 2d0aa858696d
Revises: 79a46400e1b7
Create Date: 2025-02-14 12:22:59.889386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0aa858696d'
down_revision: Union[str, None] = '79a46400e1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_chunks', 'chunk_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_chunks', sa.Column('chunk_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
