"""Modifica ordine campi tabella transcripts

Revision ID: 526d0157cd53
Revises: 11ce52399412
Create Date: 2025-02-14 12:42:16.310826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526d0157cd53'
down_revision: Union[str, None] = '11ce52399412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
