"""Correzione 2, relazione tra transcripts e transcription_chunks

Revision ID: 54706a9af6a8
Revises: 2d0aa858696d
Create Date: 2025-02-14 12:32:27.746073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54706a9af6a8'
down_revision: Union[str, None] = '2d0aa858696d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
