"""Aggiunto campo word_doc come BLOB in Transcript

Revision ID: 78b3304a86a9
Revises: d4f74958c2c7
Create Date: 2025-03-06 07:01:02.611907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b3304a86a9'
down_revision: Union[str, None] = 'd4f74958c2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('word_doc', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'word_doc')
    # ### end Alembic commands ###
