"""Aggiunta tabella transcription_chunks e modifica transcripts

Revision ID: 79a46400e1b7
Revises: 8a19719003b6
Create Date: 2025-02-14 12:11:40.262412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a46400e1b7'
down_revision: Union[str, None] = '8a19719003b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_chunks_id'), 'transcription_chunks', ['id'], unique=False)
    op.add_column('transcripts', sa.Column('chunk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transcripts', 'transcription_chunks', ['chunk'], ['id'])
    op.drop_column('transcripts', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.drop_column('transcripts', 'chunk')
    op.drop_index(op.f('ix_transcription_chunks_id'), table_name='transcription_chunks')
    op.drop_table('transcription_chunks')
    # ### end Alembic commands ###
