"""Aggiunta tabella transcriptions_summaries

Revision ID: 8b022a90b675
Revises: 0053fc0bb891
Create Date: 2025-02-17 06:24:57.384143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b022a90b675'
down_revision: Union[str, None] = '0053fc0bb891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
