"""add segments to Transcript

Revision ID: 941ca1f023f1
Revises: 78b3304a86a9
Create Date: 2025-05-02 19:26:27.573761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941ca1f023f1'
down_revision: Union[str, None] = '78b3304a86a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'segments')
    # ### end Alembic commands ###
